
name: Satel-registry-push
description: Pushes branch on docker registry
inputs:
  app-name:
    description: Name of the webapp
    required: true
  # server-dir:
  #   description: Directory for server
  #   required: false  
  satel-docker-user:
    description: Username for satel docker registry
    required: false 
  satel-docker-pass:
    description: Password for satel docker registry 
    required: false 
  client-docker-user:
    description: Username for client docker registry
    required: false 
  client-docker-pass:
    description: Password for client docker registry 
    required: false      
  satel-registry:
    description: Satel registry address
    required: false  
  client-registry:
    description: Client registry address
    required: false   
  dockerfile:
    description: Dockerfile 
    required: false
    default: Dockerfile
  current-branch-name: 
    description: Provides current branch name 
    required: false    
  tag-name: 
    description: Provides current tag name action.yml
    required: false 
    
outputs:
  registry:  # id of output
    description: 'Satel or client registry'
    value:  ${{ steps.registry.outputs.registry }}
  clean_branch_name:
    description: 'Branch name that was pushed to registry'
    value:  ${{ steps.registry.outputs.CLEAN_BRANCH_NAME }}
    
runs:
  using: "composite"
  steps:
    - run: ${{ github.action_path }}/deploy_server.sh ${{ inputs.app-name }} ${{ inputs.satel-docker-user }} ${{ inputs.satel-docker-pass }} ${{ inputs.client-docker-user }} ${{ inputs.client-docker-pass }} ${{ inputs.satel-registry }} ${{ inputs.client-registry }} ${{ inputs.dockerfile }} ${{ inputs.current-branch-name }} ${{ inputs.tag-name }} 
      id: registry
      shell: bash
    
    - id: registryprint
      run: echo "webaruuner{{ steps.registry.outputs.registry}}"
      shell: bash 
